/*
 * Decompiled with CFR 0.152.
 */
package com.yourname.companion.runtime;

import com.yourname.companion.data.CompanionState;
import com.yourname.companion.runtime.MovementOwner;
import com.yourname.companion.runtime.Vec3;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public final class CompanionRuntimeState {
    public CompanionState state = CompanionState.DESPAWNED;
    public long lastRepathTick;
    public Vec3 lastPosition = new Vec3();
    public Vec3 stayAnchor;
    public int stuckTicks;
    public String combatTargetId;
    public long lastCombatScanTick;
    public int combatStickyTicks;
    public boolean pendingKillCredit;
    public String recentCombatDamageTargetId;
    public long recentCombatDamageTick;
    public long lastRangedAttackTick;
    public long lastMeleeAttackTick;
    public long lastVisualGuardTick;
    public long lastCombatPathTick;
    public String combatBlockedTargetId;
    public long combatBlockedUntilTick;
    public boolean regenWasInCombat;
    public long regenStartTick;
    public long regenLastApplyTick;
    public String lootTargetId;
    public long lastLootScanTick;
    public long lastLootDebugTick;
    public long lootNoSpaceUntilTick;
    public int lootUnreachableTicks;
    public long lastDepositTick;
    public boolean depositRequested;
    public String depositBlockedChestKey;
    public long depositBlockedUntilTick;
    public Vec3 farmTargetPos;
    public String farmTaskType;
    public String farmPlantSeedId;
    public long lastFarmScanTick;
    public int farmUnreachableTicks;
    public String farmLastTargetKey;
    public int farmStuckRepeatCount;
    public String farmBlockedTargetKey;
    public long farmBlockedUntilTick;
    public String farmHarvestVerifyTargetKey;
    public int farmHarvestVerifyX;
    public int farmHarvestVerifyY;
    public int farmHarvestVerifyZ;
    public long farmHarvestVerifyTick1;
    public long farmHarvestVerifyTick2;
    public String farmHarvestBeforeId;
    public boolean farmHarvestAttempted;
    public final Map<String, Long> farmNoHarvestUntilByTargetKey = new HashMap<String, Long>();
    public final Set<String> farmWateredTargetKeys = new HashSet<String>();
    public String farmTurnTargetKey;
    public long farmTurnUntilTick;
    public boolean farmDepositPending;
    public long lastFarmIdleLogTick;
    public long lastFarmMoveTick;
    public long lastFarmPathTick;
    public long lastFarmActionTick;
    public long nextFarmScanTick;
    public String farmStatusText;
    public MovementOwner movementOwner = MovementOwner.NONE;
    public long movementOwnerChangedTick;
    public Vec3 mineTargetPos;
    public String mineTargetBlockId;
    public boolean miningActive;
    public boolean mineForSpecific;
    public int mineSearchRadius;
    public long lastMineScanTick;
    public int mineUnreachableTicks;
    public int mineStepX;
    public int mineStepY;
    public int mineStepZ;
    public int mineClearanceY;
    public int mineEmptyForwardConsecutive;
    public String mineStatusText;
    public long nextMineAttemptTick;
    public Vec3 mineAnchorPos;
    public boolean mineMoveToAnchorPending;
    public long lastMineMoveTick;
    public long lastMineFaceTick;
    public long lastMineDiagTick;
    public boolean mineLaneLocked;
    public int mineLaneX;
    public int mineLaneZ;
    public long lastMineDebugTick;
    public String lastMineDebugStatus;
    public long mineFallDetectedTick;
    public Vec3 mineLastMinedPos;
    public double mineLastTargetDistance = -1.0;
    public long mineLastForwardProgressTick;
    public String mineTargetPriority;
    public final Map<String, Long> mineBlockedTargetUntilByKey = new HashMap<String, Long>();
    public Vec3 minePendingBreakPos;
    public String minePendingBreakBlockId;
    public boolean mineDepositOnlyMined;
    public boolean mineReturnToLoadedArea;
    public boolean mineShiftLaneAfterReturn;
    public int mineShiftLaneAfterReturnAttempt;
    public Vec3 mineShiftLaneAfterReturnOrigin;
    public int mineBoundaryTurnPhase;
    public int mineBoundaryTurnNextSide = 1;
    public int mineBoundaryTurnOriginalStepX;
    public int mineBoundaryTurnOriginalStepZ;
    public final Set<String> mineCollectedItemIds = new HashSet<String>();
    public boolean maxDefendMode;
    public boolean commandActive;
    public Vec3 patrolAnchor;
    public Vec3 patrolForwardTarget;
    public boolean patrolReturning;
    public int patrolStepX;
    public int patrolStepZ;
    public Vec3 freeRoamAnchor;
    public Vec3 freeRoamTarget;
    public long nextFreeRoamRetargetTick;
    public double freeDirX;
    public double freeDirZ;
    public long lastFreeBreakTick;
    public long stateEnteredTick;
    public long currentTick;
    public long lastStartStateNudgeTick;
    public int appearanceCaptureAttempts;
    public long nextAppearanceCaptureTick;
    public int followBootstrapTicks;
    public boolean wasHolding;
    public long lastFollowTargetRefreshTick;
    public long launchSuppressUntilMs;
    public long lastLaunchSuppressLogMs;
    public long lastTeleportTick;
    public long lastSuffocationRecoverTick;
    public long lastFollowDebugTick;
    public long lastFollowTeleportLogTick;
    public boolean stateDebugLogged;
    public String lastFollowMode;
    public double lastFollowTraceDistance;
    public Vec3 lastFollowMoveSample;
    public long lastFollowMoveSampleTick;
    public long lastInventorySnapshotTick;
    public long lastInventoryLayoutRepairTick;
    public long lastAppearanceSnapshotTick;
    public long recruitAppearanceFinalizeTick;
    public String reactiveAttackerId;
    public long reactiveAttackerUntilMs;
    public long invalidEntityRefSinceTick;
    public boolean miningHeldVisualApplied;
    public String miningHeldPreviousItemId;
    public int miningHeldPreviousQuantity;
    public boolean farmHeldVisualApplied;
    public String farmHeldVisualToolId;
    public String farmHeldPreviousItemId;
    public int farmHeldPreviousQuantity;
    public boolean farmHeldVisualSynthetic;
    public boolean farmHeldVisualSlotZeroWasTool;

    public void reset() {
        this.state = CompanionState.DESPAWNED;
        this.lastRepathTick = 0L;
        this.lastPosition = new Vec3();
        this.stayAnchor = null;
        this.stuckTicks = 0;
        this.combatTargetId = null;
        this.lastCombatScanTick = 0L;
        this.combatStickyTicks = 0;
        this.pendingKillCredit = false;
        this.recentCombatDamageTargetId = null;
        this.recentCombatDamageTick = 0L;
        this.lastRangedAttackTick = 0L;
        this.lastMeleeAttackTick = 0L;
        this.lastVisualGuardTick = 0L;
        this.lastCombatPathTick = 0L;
        this.combatBlockedTargetId = null;
        this.combatBlockedUntilTick = 0L;
        this.regenWasInCombat = false;
        this.regenStartTick = 0L;
        this.regenLastApplyTick = 0L;
        this.lootTargetId = null;
        this.lastLootScanTick = 0L;
        this.lastLootDebugTick = 0L;
        this.lootNoSpaceUntilTick = 0L;
        this.lootUnreachableTicks = 0;
        this.lastDepositTick = 0L;
        this.depositRequested = false;
        this.depositBlockedChestKey = null;
        this.depositBlockedUntilTick = 0L;
        this.farmTargetPos = null;
        this.farmTaskType = null;
        this.farmPlantSeedId = null;
        this.lastFarmScanTick = 0L;
        this.farmUnreachableTicks = 0;
        this.farmLastTargetKey = null;
        this.farmStuckRepeatCount = 0;
        this.farmBlockedTargetKey = null;
        this.farmBlockedUntilTick = 0L;
        this.farmHarvestVerifyTargetKey = null;
        this.farmHarvestVerifyX = 0;
        this.farmHarvestVerifyY = 0;
        this.farmHarvestVerifyZ = 0;
        this.farmHarvestVerifyTick1 = 0L;
        this.farmHarvestVerifyTick2 = 0L;
        this.farmHarvestBeforeId = null;
        this.farmHarvestAttempted = false;
        this.farmNoHarvestUntilByTargetKey.clear();
        this.farmWateredTargetKeys.clear();
        this.farmTurnTargetKey = null;
        this.farmTurnUntilTick = 0L;
        this.farmDepositPending = false;
        this.lastFarmIdleLogTick = 0L;
        this.lastFarmMoveTick = 0L;
        this.lastFarmPathTick = 0L;
        this.lastFarmActionTick = 0L;
        this.nextFarmScanTick = 0L;
        this.farmStatusText = null;
        this.movementOwner = MovementOwner.NONE;
        this.movementOwnerChangedTick = 0L;
        this.mineTargetPos = null;
        this.mineTargetBlockId = null;
        this.miningActive = false;
        this.mineForSpecific = false;
        this.mineSearchRadius = 0;
        this.lastMineScanTick = 0L;
        this.mineUnreachableTicks = 0;
        this.mineStepX = 0;
        this.mineStepY = 0;
        this.mineStepZ = 0;
        this.mineClearanceY = 0;
        this.mineEmptyForwardConsecutive = 0;
        this.mineStatusText = null;
        this.nextMineAttemptTick = 0L;
        this.mineAnchorPos = null;
        this.mineMoveToAnchorPending = false;
        this.lastMineMoveTick = 0L;
        this.lastMineFaceTick = 0L;
        this.lastMineDiagTick = 0L;
        this.mineLaneLocked = false;
        this.mineLaneX = 0;
        this.mineLaneZ = 0;
        this.lastMineDebugTick = 0L;
        this.lastMineDebugStatus = null;
        this.mineFallDetectedTick = 0L;
        this.mineLastMinedPos = null;
        this.mineLastTargetDistance = -1.0;
        this.mineLastForwardProgressTick = 0L;
        this.mineTargetPriority = null;
        this.mineBlockedTargetUntilByKey.clear();
        this.minePendingBreakPos = null;
        this.minePendingBreakBlockId = null;
        this.mineDepositOnlyMined = false;
        this.mineReturnToLoadedArea = false;
        this.mineShiftLaneAfterReturn = false;
        this.mineShiftLaneAfterReturnAttempt = 0;
        this.mineShiftLaneAfterReturnOrigin = null;
        this.mineBoundaryTurnPhase = 0;
        this.mineBoundaryTurnNextSide = 1;
        this.mineBoundaryTurnOriginalStepX = 0;
        this.mineBoundaryTurnOriginalStepZ = 0;
        this.mineCollectedItemIds.clear();
        this.maxDefendMode = false;
        this.commandActive = false;
        this.patrolAnchor = null;
        this.patrolForwardTarget = null;
        this.patrolReturning = false;
        this.patrolStepX = 0;
        this.patrolStepZ = 0;
        this.freeRoamAnchor = null;
        this.freeRoamTarget = null;
        this.nextFreeRoamRetargetTick = 0L;
        this.freeDirX = 0.0;
        this.freeDirZ = 0.0;
        this.lastFreeBreakTick = 0L;
        this.stateEnteredTick = 0L;
        this.lastStartStateNudgeTick = 0L;
        this.appearanceCaptureAttempts = 0;
        this.nextAppearanceCaptureTick = 0L;
        this.followBootstrapTicks = 0;
        this.wasHolding = false;
        this.lastFollowTargetRefreshTick = 0L;
        this.launchSuppressUntilMs = 0L;
        this.lastLaunchSuppressLogMs = 0L;
        this.lastTeleportTick = 0L;
        this.lastSuffocationRecoverTick = 0L;
        this.lastFollowDebugTick = 0L;
        this.lastFollowTeleportLogTick = 0L;
        this.lastFollowMode = null;
        this.lastFollowTraceDistance = 0.0;
        this.lastFollowMoveSample = null;
        this.lastFollowMoveSampleTick = 0L;
        this.lastInventorySnapshotTick = 0L;
        this.lastInventoryLayoutRepairTick = 0L;
        this.lastAppearanceSnapshotTick = 0L;
        this.recruitAppearanceFinalizeTick = 0L;
        this.reactiveAttackerId = null;
        this.reactiveAttackerUntilMs = 0L;
        this.invalidEntityRefSinceTick = 0L;
        this.miningHeldVisualApplied = false;
        this.miningHeldPreviousItemId = null;
        this.miningHeldPreviousQuantity = 0;
        this.farmHeldVisualApplied = false;
        this.farmHeldVisualToolId = null;
        this.farmHeldPreviousItemId = null;
        this.farmHeldPreviousQuantity = 0;
        this.farmHeldVisualSynthetic = false;
        this.farmHeldVisualSlotZeroWasTool = false;
    }
}

